- name: Add Rancher Helm repo
  command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

- name: Update Helm repos
  command: helm repo update

- name: Install Rancher
  shell: >
    helm install rancher rancher-latest/rancher
    --namespace cattle-system
    --set hostname={{ rancher_hostname }}
    --set replicas=1
    --set bootstrapPassword={{ rancher_bootstrap_password }}
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for Rancher deployment
  shell: |
    kubectl -n cattle-system rollout status deploy/rancher

