- name: Install K3s in agent mode (joins server at {{ k3s_server_url }})
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" \
    K3S_URL="{{ k3s_server_url }}" K3S_TOKEN="{{ k3s_token }}" sh -s - agent
  args:
    creates: /usr/local/bin/k3s-agent

